import { Link } from 'react-router-dom'
import NavBar from '../components/NavBar'
import MindMapRadial from '../components/MindMapRadial'
import { useAppStore } from '../store/useAppStore'

export default function MindMapPage() {
  const { roadmap } = useAppStore()

  if (!roadmap) {
    return (
      <div className="min-h-screen">
        <NavBar />
        <main className="max-w-2xl mx-auto px-6 py-24 text-center">
          <h1 className="font-display text-2xl font-semibold mb-3">No mind map yet</h1>
          <Link to="/topic" className="text-cortex">Generate a roadmap first →</Link>
        </main>
      </div>
    )
  }

  return (
    <div className="min-h-screen">
      <NavBar />
      <main className="max-w-6xl mx-auto px-6 py-10">
        <p className="font-mono text-xs text-cortex uppercase tracking-[0.2em] mb-2">
          Generated by Mind Map Agent
        </p>
        <h1 className="font-display text-3xl font-semibold mb-1">{roadmap.title}</h1>
        <p className="text-dim text-sm mb-6">
          Drag nodes to explore relationships. Node size reflects difficulty level.
        </p>

        <MindMapRadial data={roadmap.mind_map as any} />
      </main>
    </div>
  )
}
